# Here we will create a simple Neural Network from Scratch.
**To get an intuation how Neural Network works under the hood**

![A simple Neural Network](https://machinelearningknowledge.ai/wp-content/uploads/2019/10/Backpropagation.gif)

![A neural network](https://i.gifer.com/6fyP.gif)



# Feed Forward Neural Network
**We can divide the whole Neural Network Learning process into 2 General Parts:**

    1. Feed Forward (When it is learning pattern from the given data)
    2. Backpropagation (Error Correction)

**Now let's focus on Feed Forward Neural Network**    
![FFNNs](https://miro.medium.com/v2/1*pO5X2c28F1ysJhwnmPsy3Q.gif)

# Model Architecture

## 1. Input Layer with 2 Nodes for 2 input features.
## 2. Two Hidden Layers -> ReLU activation Function.
## 3. One Output Layer -> 1 Node with Sigmoid activation.
## 4. We wrote a code for Softmax Activation function also but did not implement it in the code.

In [1]:
import numpy as np # One most important note is that we are using numpy
np.random.seed(42) # seed = 42 because it gives nice output of feed forward that why:3

Normally, while reading about neural networks, we pass a single sample of data. But in an actual scenario, the model will not work with a single data point; it will work with a batch of data. For example, each batch will contain as many samples as the batch size specifies. It’s definitely not going to be just one sample of data. That’s why, in an actual case, we need to switch our perspective from scalar to matrix.

In [2]:
"""input matrix from input layer"""
X = np.random.rand(4,2) # 4 rows-> 4 samples, 2 cols-> 2 input features. [No output layer yet..haha]
X # and boom..we've created our input matrix

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615]])

In [3]:
""" Initializaton and Calculation"""
class Dense_layer:
    
    print(""" So here we are initializing the weight matrix and bias matrix
    using the input layer's num of nodes and current layer's num of nodes""")
    
    def __init__(self,input_layer_nodes,current_layer_nodes): # weight and bias matrix initalization 
        
        self.weight = np.random.randn(input_layer_nodes,current_layer_nodes)*0.01 # Weight Matrix
        self.bias = np.zeros((1,current_layer_nodes)) # 0 initialization -> Bias Matrix

   
    print("""now that we have set our:
                                1. weight matrix
                                2. bias vector,
                                3. and we also have our input matrix, 
       now we are ready for feed forward Action.....yeeeeaaaa!!!
    """)
    
    def feed_forward(self,input_matrix): # we are sending the input matrix (X) here
        self.output = np.dot(input_matrix,self.weight)+self.bias # This is the weighted summation + bias
                                                                # Z = (input matrix).(weight matrix) + bias matrix
        return self.output 
    """
        The weighted summation is also Completed. we got our (Z). Yeeeaaaaa!!!
        Now we are ready for activation function. We've to put Z inside activation function.
    """

 So here we are initializing the weight matrix and bias matrix
    using the input layer's num of nodes and current layer's num of nodes
now that we have set our:
                                1. weight matrix
                                2. bias vector,
                                3. and we also have our input matrix, 
       now we are ready for feed forward Action.....yeeeeaaaa!!!
    


In [4]:
print("""ReLU activation Function""")
class Activation_relu:
    def feed_forward(self, Z):
        self.output = np.maximum(0,Z) # relu be like no negetivity here, only positivity..haha
        return self.output

print("""Sigmoid Activation Function""") 
class Activation_sigmoid:
    def feed_forward(self,Z):
        self.output = 1/(1+np.exp(-Z))
        return self.output 

print("Softmax activation")
class Activation_softmax:
    def feed_forward(self,z):
        exp_mat = np.exp(z- np.max(z,axis=1,keepdims=True)) # helping with overflowing by shriking the values
        normalize_mat = exp_mat/np.sum(exp_mat, axis=1,keepdims=True)
        self.output = normalize_mat
        return self.output

ReLU activation Function
Sigmoid Activation Function
Softmax activation


In [5]:
"""Layer and Activation function defined"""
layer1 = Dense_layer(2,4) # input node, num of node in h1, so the moment you made the obj of the dense clss constructor will initial it automatically
activation1 = Activation_relu() #define activation

layer2 = Dense_layer(4,2)
activation2 = Activation_relu()

layer3 = Dense_layer(2,1)
output_activation = Activation_sigmoid()     

# Now the dense connection
#Layer 1:
Z1 = layer1.feed_forward(X)
layer1_output = activation1.feed_forward(Z1)

# Layer 2:
Z2 = layer2.feed_forward(layer1_output)
layer2_output = activation2.feed_forward(Z2)

# Output Layer
Z3 = layer3.feed_forward(layer2_output)
final_output = output_activation.feed_forward(Z3)



print("Input Matrix:\n", X)
print("\nLayer 1 Weights:\n", layer1.weight)
print("\nLayer 1 Bias:\n", layer1.bias)


print("\nLayer 1 (Z1):\n", Z1)
print("\nAfter ReLU (Layer1 Output):\n", layer1_output)

print("\nLayer 2 (Z2):\n", Z2)
print("\nAfter ReLU (Layer2 Output):\n", layer2_output)

print("\nLayer 3 (Z3):\n", Z3)
print("\nFinal Output (Sigmoid):\n", final_output)

Input Matrix:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]
 [0.05808361 0.86617615]]

Layer 1 Weights:
 [[ 0.01579213  0.00767435 -0.00469474  0.0054256 ]
 [-0.00463418 -0.0046573   0.00241962 -0.0191328 ]]

Layer 1 Bias:
 [[0. 0. 0. 0.]]

Layer 1 (Z1):
 [[ 0.00150901 -0.00155341  0.000542   -0.01615772]
 [ 0.00878545  0.00282945 -0.001988   -0.00748251]
 [ 0.00174096  0.00047083 -0.00035502 -0.00213812]
 [-0.00309675 -0.00358829  0.00182313 -0.01625724]]

After ReLU (Layer1 Output):
 [[0.00150901 0.         0.000542   0.        ]
 [0.00878545 0.00282945 0.         0.        ]
 [0.00174096 0.00047083 0.         0.        ]
 [0.         0.         0.00182313 0.        ]]

Layer 2 (Z2):
 [[-3.09506258e-05 -1.61396458e-05]
 [-1.80199342e-04 -4.05080499e-05]
 [-3.47988281e-05 -8.30963637e-06]
 [-1.65544756e-05 -2.57481578e-05]]

After ReLU (Layer2 Output):
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Layer 3 (Z3):
 [[0.]
 [0.]
 [0.]
 [0.]]

Final Output (Sigmoid):


# This is feed forwar, it will change according to problem type and how you want to organized our Architecture.